AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
#  MyLambdaFunction:
#    Type: 'AWS::Serverless::Function'
#    Properties:
#      Handler: index.handler
#      Runtime: nodejs20.x
#      CodeUri: .
#      MemorySize: 128
#      Timeout: 30
#      Environment:
#        Variables:
#          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
#      Events:
#        MyApi:
#          Type: Api
#          Properties:
#            Path: /myendpoint
#            Method: get

  # MyVPC:
  #   Type: AWS::EC2::VPC
  #   Properties:
  #     CidrBlock: 10.0.0.0/16

  # MySubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     CidrBlock: 10.0.0.0/24

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - subnet-02c217f126c0ce1d5

  MyElasticacheRedis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: vpc-066e6a637e37f2752
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0



  PostCustomerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postCustomer
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
      Events:
        PostCustomerApi:
          Type: Api
          Properties:
            Path: /customers
            Method: post

  GetCustomerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getCustomer
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
      Events:
        GetCustomerByIdApi:
          Type: Api
          Properties:
            Path: /customers/{customerId}
            Method: get

  PostOrderLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postOrder
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
      Events:
        PostOrderApi:
          Type: Api
          Properties:
            Path: /orders
            Method: post

  GetOrderLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getOrder
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
      Events:
        GetOrderByIdApi:
          Type: Api
          Properties:
            Path: /order/{orderId}
            Method: get

  PostOrderItemLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.postOrderItem
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
      Events:
        PostOrderItemsApi:
          Type: Api
          Properties:
            Path: /orderItems
            Method: post

  GetOrderItemLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getOrderItem
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
      Events:
        GetOrderItemByIdApi:
          Type: Api
          Properties:
            Path: /orderItems/{orderItemId}
            Method: get

